.PHONY: build test clean fmt lint audit check

nix:
	nix-shell

build:
	cargo build

test:
	cargo test

clean:
	cargo clean

fmt:
	cargo fmt

lint:
	cargo clippy

audit:
	cargo audit

check:
	cargo check
